---
abstract: 'Hook into opcode execution'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::Depends: 0.302
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-Hooks-OP-PPAddr
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rafl/b-hooks-op-ppaddr.git
version: 0.03
