--- #YAML:1.0
name:               Set-Object
version:            1.28
abstract:           Unordered collections (sets) of Perl Objects
author:
    - Jean-Louis Leroy and Sam Vilain
license:            Artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Scalar::Util:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
