---
abstract: 'roles with composition parameters'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Fatal: 0
  Test::Moose: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-Parameterized
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 2.0300
  perl: 5.8.1
resources:
  homepage: http://github.com/sartak/MooseX-Role-Parameterized/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/sartak/MooseX-Role-Parameterized.git
    web: http://github.com/sartak/MooseX-Role-Parameterized/tree
version: 1.00
