---
abstract: 'A glimpse at an Enlightened Perl (testing tools).'
author:
  - 'Chris Prather <chris@prather.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Kensho-Testing
no_index:
  directory:
    - inc
    - t
requires:
  Devel::Cover: 0
  Test::Exception: 0
  Test::Memory::Cycle: 0
  Test::Most: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.28
