---
abstract: 'Validate method/function parameters'
author:
  - 'Dave Rolsky, <autarch@urth.org> and Ilya Martynov <ilya@martynov.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Params-Validate
requires:
  Attribute::Handlers: 0.79
  Scalar::Util: 1.10
  perl: v5.8.1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Params-Validate
  repository: git://git.urth.org/Params-Validate.git
version: 1.00
