--- #YAML:1.0
name:               MooseX-Clone
version:            0.05
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Visitor:        0.24
    Hash::Util::FieldHash::Compat:  0
    Moose:                0.74
    namespace::clean:     0.08
    Test::use::ok:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
