---
abstract: 'Capture STDOUT and STDERR from Perl, XS or external programs'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Config: 0
  File::Find: 0
  IO::File: 0
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112580'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Capture-Tiny
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Capture::Tiny:
    file: lib/Capture/Tiny.pm
    version: 0.15
requires:
  Carp: 0
  Exporter: 0
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  Scalar::Util: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Capture-Tiny
  homepage: https://github.com/dagolden/capture-tiny
  repository: https://github.com/dagolden/capture-tiny.git
version: 0.15
