---
abstract: 'Manage deprecation warnings for your distribution'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Package-DeprecationManager
requires:
  Carp: 0
  List::MoreUtils: 0
  Params::Util: 0
  Sub::Install: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Package-DeprecationManager
  repository: git://git.moose.perl.org/Package-DeprecationManager.git
version: 0.11
