---
abstract: 'Code coverage metrics for Perl'
author:
  - 'Paul Johnson (pjcj@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Cover
no_index:
  directory:
    - t
    - inc
    - tests
    - utils
recommends:
  JSON::PP: 0
  PPI::HTML: 1.07
  Parallel::Iterator: 0
  Perl::Tidy: 20060719
  Pod::Coverage: 0.06
  Pod::Coverage::CountParents: 0
  Template: 2
  Test::Differences: 0
  perl: 5.008002
requires:
  Digest::MD5: 0
  Storable: 0
  perl: 5.006001
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Devel-Cover
  homepage: http://www.pjcj.net/perl.html
  license: http://dev.perl.org/licenses
  repository: http://github.com/pjcj/Devel--Cover
  x_MailingList: http://lists.perl.org/list/perl-qa.html
version: 0.79
