--- #YAML:1.0
name:                Carp-Clan
version:             6.04
abstract:            Report errors from perspective of caller of a "clan" of modules
license:             perl
author:              
    - Steffen Beyer <STBEY@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::Exception:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
