---
abstract: 'Test strings and data structures and show differences if not ok'
author:
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Differences
provides:
  Test::Differences:
    file: lib/Test/Differences.pm
    version: 0.61
requires:
  Data::Dumper: 2.126
  Test::More: 0
  Text::Diff: 0.35
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/Ovid/Test-Differences
version: 0.61
