---
abstract: 'Organise your Moose types in libraries'
author:
  - "Robert \"phaylon\" Sedlacek <rs@474.at>"
build_requires:
  FindBin: 0
  Test::Fatal: 0
  Test::Moose: 0
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types
requires:
  Carp: 0
  Carp::Clan: 6.00
  Moose: 1.06
  Scalar::Util: 1.19
  Sub::Install: 0.924
  Sub::Name: 0
  namespace::clean: 0.19
  perl: v5.8.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooseX-Types
  repository: git://git.moose.perl.org/MooseX-Types.git
version: 0.31
