# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PadWalker
version:      1.7
license:      perl
version_from: PadWalker.pm
installdirs:  site
requires:
  perl: 5.008002

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
