---
abstract: 'Declare class attributes Moose-style'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Scalar::Util: 0
  Test::Fatal: 0
  Test::More: 0.88
  Test::Requires: 0.05
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-ClassAttribute
requires:
  Moose: 1.23
  namespace::autoclean: 0.11
  namespace::clean: 0.20
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooseX-ClassAttribute
  repository: git://git.moose.perl.org/MooseX-ClassAttribute.git
version: 0.26
