---
abstract: 'XS implementation of parts of Class::Load'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Module::Build: 0.3601
  Test::Fatal: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Load-XS
requires:
  Class::Load: 0.11
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Class-Load-XS
  repository: git://git.urth.org/Class-Load-XS.git
version: 0.03
